# Generated by Django 6.0.3 on 2026-04-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('transaction_type', models.CharField(choices=[('rental', 'Rental Income'), ('late_fee', 'Late Fee'), ('refund', 'Refund'), ('discount', 'Discount Applied')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('film_id', models.IntegerField(blank=True, null=True)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'revenue_transactions',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'transaction_type'], name='revenue_tra_date_b68d6a_idx'), models.Index(fields=['film_id', 'date'], name='revenue_tra_film_id_5652e2_idx')],
            },
        ),
    ]
