# Generated by Django 6.0.3 on 2026-04-05 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revenuetransaction',
            options={'ordering': ['-date'], 'verbose_name': 'Revenue Transaction', 'verbose_name_plural': 'Revenue Transactions'},
        ),
        migrations.AddField(
            model_name='revenuetransaction',
            name='store_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Store location identifier', null=True),
        ),
        migrations.AddField(
            model_name='revenuetransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='revenuetransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Transaction amount in USD', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='revenuetransaction',
            name='customer_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Reference to customer (denormalized for analytics)', null=True),
        ),
        migrations.AlterField(
            model_name='revenuetransaction',
            name='date',
            field=models.DateField(db_index=True, help_text='Transaction date (used for time-series analytics)'),
        ),
        migrations.AlterField(
            model_name='revenuetransaction',
            name='film_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Reference to film (denormalized for analytics)', null=True),
        ),
        migrations.AlterField(
            model_name='revenuetransaction',
            name='transaction_id',
            field=models.CharField(db_index=True, help_text='Unique external transaction identifier', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='revenuetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('rental', 'Rental Income'), ('late_fee', 'Late Fee'), ('refund', 'Refund'), ('discount', 'Discount Applied')], db_index=True, help_text='Category of revenue transaction', max_length=20),
        ),
        migrations.AddIndex(
            model_name='revenuetransaction',
            index=models.Index(fields=['customer_id', 'date'], name='revenue_tra_custome_f5332a_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuetransaction',
            index=models.Index(fields=['store_id', 'date'], name='revenue_tra_store_i_cee8b8_idx'),
        ),
    ]
