# Generated by Django 6.0.3 on 2026-04-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('store_id', models.IntegerField()),
                ('address_id', models.IntegerField()),
                ('active', models.BooleanField()),
                ('create_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactCustomerBehavior',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('store_id', models.IntegerField()),
                ('active', models.BooleanField()),
                ('total_rentals', models.IntegerField()),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_rental_duration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('days_since_last_rental', models.IntegerField()),
                ('last_rental_date', models.DateField()),
                ('is_churn', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'fact_customer_behavior',
            },
        ),
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_file', models.CharField(max_length=255)),
                ('training_data', models.CharField(max_length=255)),
                ('training_date', models.DateTimeField()),
                ('model_summary', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreChurnSummary',
            fields=[
                ('store_id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_customers', models.IntegerField()),
                ('churned_customers', models.IntegerField()),
                ('churn_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'store_churn_summary',
            },
        ),
    ]
